/************************************************************************
***
***  shift_to_register_macros
***
***  Bobby Winters, bwinters@pittstate.edu, 4/4/2025
***
************************************************************************/
;
; This file contains parameters for use with shift registers
;
;shift register parameters
;needed for shift_to_register.asm
;
;----------------------------------------------------------------------------
.equ CLOCK=5
.equ LATCH=4
.equ DATA=3
.equ CARRY=0
.equ word_length=0x10
;-----------------------------------------------------------------------------